apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-metrics-exporter
  description: Auxiliary metrics exporter for the backend service
  annotations:
    github.com/project-slug: meridian-demo/backend
  tags:
    - backend
    - metrics
spec:
  type: service
  lifecycle: production
  owner: group:default/engineering
  system: backend
